language: go

go:
  - "1.x"
  - master

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(find . -path ./vendor -prune -o -path ./.git -prune -o -iname '*.go' -print | xargs gofmt -d -s)
  - go test -v ./...
